(() => {
  const KEY='tgg-business-v1';
  const catalog=[
    {id:'studio-row',name:'Studio Row',type:'MUSIC',unlock:1,detail:'Recording rooms, producers and late-night sessions.'},
    {id:'sneaker-district',name:'Sneaker District',type:'STYLE',unlock:2,detail:'Sneakers, streetwear and character upgrades.'},
    {id:'media-block',name:'Media Block',type:'MEDIA',unlock:3,detail:'Photo sets, interviews and release promotion.'},
    {id:'executive-ave',name:'Executive Ave',type:'BUSINESS',unlock:5,detail:'Properties, offices and higher-tier opportunities.'}
  ];
  let state={discovered:[],selected:null,assets:{status:'offline_ready',properties:[],propertyUpgrades:[],vehicles:[]}};
  function load(){try{state={...state,...JSON.parse(localStorage.getItem(KEY)||'{}')}}catch(e){}if(!Array.isArray(state.discovered))state.discovered=[]}
  function save(){localStorage.setItem(KEY,JSON.stringify(state))}
  function sync(){const level=Number(window.TGGGame?.getState?.()?.level)||1;catalog.forEach(x=>{if(level>=x.unlock&&!state.discovered.includes(x.id))state.discovered.push(x.id)});save();return state}
  function available(){sync();return catalog.filter(x=>state.discovered.includes(x.id))}
  function open(){render();window.TGGGame?.show?.('businessBoard');loadAssets()}
  function render(){
    let el=document.getElementById('businessBoard');
    if(!el){el=document.createElement('section');el.id='businessBoard';el.className='screen';document.querySelector('main')?.appendChild(el)}
    const rows=available().map(x=>'<button class="business-card" data-business="'+x.id+'"><b>'+x.name+'</b><span>'+x.type+' • LVL '+x.unlock+'</span><small>'+x.detail+'</small></button>').join('');
    el.innerHTML='<div class="panel"><p class="eyebrow">V1.13 • CITY BUSINESS + VEHICLE HUB</p><h2>KNOW THE CITY.</h2><p>Discover businesses, inspect available properties and track vehicle progression. Discovery never triggers a purchase.</p><div class="business-grid">'+rows+'</div><div id="businessDetail" class="mission-card">Select a location to inspect it.</div><div id="worldAssetsPanel" class="mission-card"><b>WORLD ASSETS</b><span id="worldAssetsStatus">Loading local/offline-ready state…</span><div id="worldProperties"></div><div id="worldVehicles"></div></div><button id="businessSync" class="primary">REFRESH WORLD ASSETS</button><button id="businessBack" class="secondary">BACK TO CITY</button></div>';
    el.querySelectorAll('[data-business]').forEach(b=>b.onclick=()=>select(b.dataset.business));
    document.getElementById('businessBack').onclick=()=>window.TGGGame?.show?.('game');    document.getElementById('businessSync').setAttribute('aria-label','Check connected world assets');
    document.getElementById('businessSync').onclick=loadAssets; renderAssets();
  }
  async function loadAssets(){const r=await window.TGGWorldSync?.worldAssetsBundle?.();state.assets=r||{ok:false,status:'offline_ready'};save();renderAssets();window.__tggToast?.(r?.ok?'WORLD ASSETS READY':'WORLD ASSETS OFFLINE-READY');return state.assets;}\n  function assetAction(type,item){const name=String(item?.name||item?.title||item?.model||item?.id||type).toUpperCase();if(type==='property'){window.TGGGame?.reward?.(75,25);window.__tggToast?.(name+' PROPERTY INSPECTED • +$75 / +25 XP');}else{window.TGGGame?.reward?.(100,30);window.__tggToast?.(name+' VEHICLE CHECKED • +$100 / +30 XP');}window.TGGWorldSync?.sync?.();window.TGGProgression?.sync?.();window.TGGCareer?.sync?.();}
  function renderAssets(){const a=state.assets||{};const s=document.getElementById('worldAssetsStatus');if(!s)return;s.textContent=(a.status||'offline_ready').toUpperCase().replaceAll('_',' ')+' • '+(a.ok?'CONNECTED':'LOCAL READY');const normalize=v=>Array.isArray(v)?v:(Array.isArray(v?.data)?v.data:(Array.isArray(v?.items)?v.items:(Array.isArray(v?.rows)?v.rows:[])));const props=normalize(a.properties);const vehicles=normalize(a.vehicles);document.getElementById('worldProperties').innerHTML=props.length?'<b>PROPERTIES</b>'+props.map((x,i)=>'<div><small>'+String(x.name||x.title||x.id||'Property')+'</small><button class="secondary world-asset-action" data-kind="property" data-index="'+i+'">INSPECT</button></div>').join(''):'<small>Property market will appear when the world transport is connected.</small>';document.getElementById('worldVehicles').innerHTML=vehicles.length?'<b>VEHICLES</b>'+vehicles.map((x,i)=>'<div><small>'+String(x.name||x.model||x.id||'Vehicle')+'</small><button class="secondary world-asset-action" data-kind="vehicle" data-index="'+i+'">CHECK</button></div>').join(''):'<small>Vehicle progression will appear when the world transport is connected.</small>';document.querySelectorAll('.world-asset-action').forEach(b=>b.onclick=()=>assetAction(b.dataset.kind,(b.dataset.kind==='property'?props:vehicles)[Number(b.dataset.index)]));}\n  function select(id){const x=catalog.find(v=>v.id===id);if(!x)return;state.selected=id;save();const el=document.getElementById('businessDetail');if(el)el.innerHTML='<b>'+x.name+'</b><span>'+x.type+'</span><small>'+x.detail+'</small><button id="businessVisit" class="primary">ENTER LOCATION</button><button id="businessActivity" class="secondary">START ACTIVITY</button>';document.getElementById('businessVisit')?.addEventListener('click',()=>visit(x));document.getElementById('businessActivity')?.addEventListener('click',()=>activity(x));}
  function visit(x){window.TGGGame?.reward?.(25,5);window.__tggToast?.(x.name.toUpperCase()+' VISITED • +$25 / +5 XP');window.TGGWorldSync?.sync?.();}
  function activity(x){const kind=x.type==='MUSIC'?'record':x.type==='MEDIA'?'photos':x.type==='STYLE'?'fitness':'lobby';window.TGGGame?.reward?.(60,20);window.__tggToast?.(x.name.toUpperCase()+' ACTIVITY COMPLETE • +$60 / +20 XP');window.TGGWorldSync?.sync?.();window.TGGProgression?.sync?.();window.TGGCareer?.sync?.();}
  load();sync();
  window.TGGBusiness={catalog,state,load,save,sync,available,open,render,select,visit,activity,loadAssets,renderAssets};
})();