(() => {
  const $=id=>document.getElementById(id);
  const GOLDEN_KEY='tgg-golden-path-v1';
  const goldenSteps=[
    {id:'create',name:'CREATE YOUR ARTIST',desc:'Choose a stage name and style.',done:s=>!!s?.name&&s.name!=='PLAYER'},
    {id:'record',name:'RECORD 3 TRACKS',desc:'Build the catalog before the first release.',done:()=>((window.TGGCareer?.career?.recordings)||0)>=3},
    {id:'release',name:'RELEASE A MIXTAPE',desc:'Turn the catalog into a finished release.',done:()=>((window.TGGCareer?.career?.mixtapes)||0)>=1},
    {id:'promo',name:'RUN MIXTAPE PROMO',desc:'Push the release through Mixtape Ave.',done:()=>((window.TGGContent?.state?.completed)||[]).includes('mixtape-promo')},
    {id:'show',name:'HIT THE STREET SHOW',desc:'Take the finished project into the city.',done:()=>((window.TGGExpansion?.state?.completed)||[]).includes('street-show')}
  ];
  function goldenState(){let s={started:false,completed:[]};try{const saved=JSON.parse(localStorage.getItem(GOLDEN_KEY)||'{}');if(saved&&typeof saved==='object'&&!Array.isArray(saved))s={...s,...saved}}catch(e){}const game=window.TGGGame?.getState?.();s.completed=goldenSteps.filter(x=>x.done(game)).map(x=>x.id);if(s.completed.length===goldenSteps.length)s.started=true;localStorage.setItem(GOLDEN_KEY,JSON.stringify(s));return s}
  function renderGolden(){const box=$('goldenPathList'),meta=$('goldenPathProgress');if(!box)return;const s=goldenState(),done=s.completed.length;if(meta)meta.textContent=`${done}/${goldenSteps.length} COMPLETE • ${Math.round(done/goldenSteps.length*100)}%`;box.innerHTML=goldenSteps.map((x,i)=>{const complete=s.completed.includes(x.id),current=!complete&&i===done;return `<div class="mission-card" style="display:flex;align-items:center;gap:12px;opacity:${complete||current?1:.55}"><b style="min-width:24px">${complete?'✓':i+1}</b><span style="flex:1"><strong>${x.name}</strong><br>${x.desc}</span><em>${complete?'COMPLETE':current?'NEXT':'LOCKED'}</em></div>`}).join('')}
  function ensureGoldenBoard(){if($('goldenPathBoard'))return;const main=document.querySelector('main');if(!main)return;const section=document.createElement('section');section.id='goldenPathBoard';section.className='screen';section.innerHTML='<div class="panel"><p class="eyebrow">CREATIVE GOLDEN PATH</p><h2>CREATE. RECORD. RELEASE. MOVE.</h2><p>Your focused artist journey from first creation to a live city moment.</p><div id="goldenPathProgress" class="stats">0/5 COMPLETE • 0%</div><div id="goldenPathList"></div><button id="goldenPathBack" class="secondary">BACK TO CITY</button></div>';main.appendChild(section);$('goldenPathBack').onclick=()=>window.TGGGame?.show?.('game')}
  function openGolden(){ensureGoldenBoard();goldenState();renderGolden();window.__tggToast?.('CREATIVE GOLDEN PATH');window.TGGGame?.show?.('goldenPathBoard')}
  function render(){const c=window.TGGCareer?.career;if(!c)return;$('careerStats').innerHTML=`<span>STUDIO LVL <b>${c.studioLevel}</b></span><span>REP <b>${c.reputation}</b></span><span>TRACKS <b>${c.recordings}</b></span><span>MIXTAPES <b>${c.mixtapes}</b></span><span>UPGRADES <b>${c.upgrades}</b></span>`}
  function open(){render();window.TGGGame?.show?.('career')}
  $('careerBtn').onclick=open;$('careerBack').onclick=()=>window.TGGGame?.show?.('game');$('recordBtn').onclick=()=>{window.TGGCareer?.record();render();renderGolden()};$('mixtapeBtn').onclick=()=>{window.TGGCareer?.mixtape();render();renderGolden()};$('upgradeBtn').onclick=()=>{window.TGGCareer?.upgrade();render();window.TGGGame?.refresh?.();renderGolden()};
  window.TGGCodexPath={steps:goldenSteps,state:goldenState,progress:()=>{const s=goldenState();return{done:s.completed.length,total:goldenSteps.length,percent:Math.round(s.completed.length/goldenSteps.length*100)}},start:openGolden,render:renderGolden};
  document.addEventListener('DOMContentLoaded',()=>{ensureGoldenBoard();renderGolden();const actions=document.querySelector('#game .actions');if(actions&&!$('goldenPathBtn')){const b=document.createElement('button');b.id='goldenPathBtn';b.textContent='CREATIVE GOLDEN PATH';b.onclick=openGolden;actions.insertBefore(b,actions.firstChild);}});
})();
