(() => {
  const KEY='tgg-daily-v1'; const DAY=()=>new Date().toISOString().slice(0,10);
  const goals=[{id:'move',label:'Hit the streets',target:10,reward:75,xp:10},{id:'cash',label:'Stack city cash',target:500,reward:125,xp:20},{id:'mission',label:'Finish a city job',target:1,reward:200,xp:35}];
  let state={day:DAY(),progress:{move:0,cash:0,mission:0},claimed:false}; const $=id=>document.getElementById(id);
  function load(){try{const x=JSON.parse(localStorage.getItem(KEY));if(x)state={...state,...x}}catch(e){}if(state.day!==DAY())state={day:DAY(),progress:{move:0,cash:0,mission:0},claimed:false};render()}
  function save(){localStorage.setItem(KEY,JSON.stringify(state));render()}
  function bump(id,n=1){if(state.claimed)return;const g=goals.find(x=>x.id===id);if(!g)return;state.progress[id]=Math.min(g.target,(state.progress[id]||0)+Math.max(0,Number(n)||0));save()}
  function render(){let box=$('tggDailyWidget');if(!box){box=document.createElement('aside');box.id='tggDailyWidget';box.innerHTML='<button id="dailyToggle" class="daily-fab">DAILY</button><div id="dailyPanel" class="daily-panel"><div class="daily-title"><b>DAILY GRIND</b><button id="dailyClose">×</button></div><div id="dailyList"></div></div>';document.body.appendChild(box);$('dailyToggle').onclick=()=>box.classList.toggle('open');$('dailyClose').onclick=()=>box.classList.remove('open')}
    const done=goals.filter(g=>state.progress[g.id]>=g.target).length;const list=$('dailyList');if(!list)return;list.innerHTML=goals.map(g=>{const p=Math.min(g.target,state.progress[g.id]||0);return '<div class="daily-row"><b>'+g.label+'</b><span>'+p+'/'+g.target+' · +$'+g.reward+' · '+g.xp+' XP</span></div>'}).join('')+'<div class="daily-progress">'+done+'/'+goals.length+' COMPLETE</div><button id="dailyClaim" class="primary daily-claim" '+(done===goals.length&&!state.claimed?'':'disabled')+'>'+(state.claimed?'REWARD CLAIMED':'CLAIM +$400 +65 XP')+'</button>';const b=$('dailyClaim');if(b)b.onclick=claim}
  function claim(){if(state.claimed||goals.some(g=>state.progress[g.id]<g.target))return;state.claimed=true;window.TGGGame?.reward?.(400,65);window.__tggToast?.('DAILY BONUS +$400 +65 XP');save()}
  function install(){const game=window.TGGGame;if(!game||game.__dailyWrapped)return;game.__dailyWrapped=true;const reward=game.reward;game.reward=(cash,xp)=>{const before=game.getState?.().cash||0;reward?.(cash,xp);const after=game.getState?.().cash||before;bump('cash',Math.max(0,after-before));bump('mission',1)};document.addEventListener('keydown',e=>{if(['ArrowUp','ArrowDown','ArrowLeft','ArrowRight','w','a','s','d'].includes(e.key))bump('move',1)});document.addEventListener('click',e=>{if(e.target?.matches?.('.controls button'))bump('move',1)})}
  window.TGGDaily={load,render,bump,getState:()=>state,install};load();install();
})();
