(() => {
  const KEY='tgg-game-v1'; const $=id=>document.getElementById(id);
  let state={name:'PLAYER',style:'Artist',x:50,y:55,cash:0,xp:0,level:1,mission:null,accepted:false,autoMode:true,heading:0};
  const screens=['menu','creator','game','pause','career','contentBoard','expansionBoard','progressionBoard','inventoryBoard','crewBoard','eventsBoard','bridge','avatar','park','studio','shops','home','media'];
  function show(id){screens.forEach(s=>$(s)?.classList.toggle('active',s===id));$('hud')?.classList.toggle('hidden',!['game','career','contentBoard','expansionBoard','progressionBoard','inventoryBoard','crewBoard','eventsBoard','bridge'].includes(id));window.TGGCareer?.render?.();window.TGGBridge?.render?.();window.TGGProgression?.render?.();window.TGGInventory?.render?.();window.TGGCrew?.render?.();window.TGGEvents?.render?.();}
  function toast(t){const el=$('toast');if(!el)return;el.textContent=t;el.classList.add('show');clearTimeout(window.__tggToastTimer);window.__tggToastTimer=setTimeout(()=>el.classList.remove('show'),1800)}
  function load(){try{const x=JSON.parse(localStorage.getItem(KEY));if(x)state={...state,...x}}catch(e){} update();window.TGGProgression?.sync?.()}
  function save(){localStorage.setItem(KEY,JSON.stringify(state));toast('GAME SAVED');window.TGGProgression?.sync?.()}
  function spend(amount){amount=Math.max(0,Number(amount)||0);if(state.cash<amount){toast('NOT ENOUGH CASH');return false}state.cash-=amount;update();save();return true}
  function activityReward(kind){const rewards={video:[120,35],photos:[80,25],premiere:[180,50],record:[100,30],mix:[90,28],release:[160,45],court:[60,20],fitness:[70,24],lobby:[40,12]};const r=rewards[kind]||[50,15];reward(r[0],r[1]);toast(kind.toUpperCase()+' COMPLETE • +$'+r[0]+' / +'+r[1]+' XP');window.TGGProgression?.sync?.();window.TGGCareer?.sync?.();window.TGGWorldSync?.sync?.()}
  function update(){ $('hudName').textContent=state.name;$('hudLevel').textContent=state.level;$('hudCash').textContent=state.cash;$('hudXp').textContent=state.xp;$('hudNext').textContent=state.level*100;$('player').style.left=state.x+'%';$('player').style.top=state.y+'%';window.TGGAvatar?.renderMini?.();$('missionStatus').textContent=state.accepted?'Mission active — finish the job.':'Find M and start a mission.';$('missionBtn').textContent=state.mission?(state.accepted?'COMPLETE MISSION':'TAKE MISSION'):'TALK TO M'}
  function addXp(n){state.xp+=Math.max(0,Number(n)||0);while(state.xp>=state.level*100){state.xp-=state.level*100;state.level++;toast('LEVEL UP — LEVEL '+state.level)}update();window.TGGProgression?.sync?.()}
  function reward(cash,xp){state.cash+=Math.max(0,Number(cash)||0);addXp(xp);save()}
  function move(dx,dy){if(dx||dy)state.heading=Math.atan2(dy,dx)*180/Math.PI;state.x=Math.max(3,Math.min(94,state.x+dx));state.y=Math.max(8,Math.min(88,state.y+dy));update();if(state.accepted&&Math.abs(state.x-72)<5&&Math.abs(state.y-36)<6)toast('You found the mission spot — hit COMPLETE MISSION')}
  function mission(){if(!state.mission){state.mission='studio-run';state.accepted=false;toast('M has a job for you.')}else if(!state.accepted){state.accepted=true;toast('MISSION ACCEPTED — get to the marked spot')}else if(Math.abs(state.x-72)<10&&Math.abs(state.y-36)<10){reward(250,50);state.mission=null;state.accepted=false;toast('MISSION COMPLETE +$250 +50 XP')}else toast('Move closer to M to finish the mission');update()}
  window.__tggToast=toast;window.TGGAutoMode={enabled:()=>true,toggle:()=>true};window.TGGGame={getState:()=>state,show,refresh:update,reward,spend,save};
  $('characterBtn').onclick=()=>window.TGGAvatar?.open?.();$('parkBtn')?.addEventListener('click',()=>show('park'));$('studioBtn')?.addEventListener('click',()=>show('studio'));$('shopsBtn')?.addEventListener('click',()=>show('shops'));$('homeBtn')?.addEventListener('click',()=>show('home'));$('mediaBtn')?.addEventListener('click',()=>show('media'));$('inventoryBtn')?.addEventListener('click',()=>show('inventoryBoard'));$('crewBtn')?.addEventListener('click',()=>show('crewBoard'));$('eventsBtn')?.addEventListener('click',()=>show('eventsBoard'));$('mediaBack')?.addEventListener('click',()=>show('game'));document.querySelectorAll('[data-media]').forEach(b=>b.addEventListener('click',()=>activityReward(b.dataset.media)));$('homeBack')?.addEventListener('click',()=>show('game'));document.querySelectorAll('[data-home]').forEach(b=>b.addEventListener('click',()=>{const a=b.dataset.home;if(a==='wardrobe'){window.TGGAvatar?.open?.();return}if(a==='save'){save();return}if(a==='career'){show('career');}}));$('shopsBack')?.addEventListener('click',()=>show('game'));document.querySelectorAll('[data-shop]').forEach(b=>b.addEventListener('click',()=>{const a=b.dataset.shop;if(a==='clothes'){window.TGGAvatar?.open?.();return}if(a==='shoes'){window.TGGAvatar?.open?.();toast('SOLE HOUSE — SHOES READY');return}if(a==='barber'){window.TGGAvatar?.open?.();toast('THE BARBER — HAIR CUSTOMIZATION');return}if(a==='jewelry'){window.TGGAvatar?.open?.();toast('ICE BOX — CHAIN CUSTOMIZATION');return}}));$('studioBack')?.addEventListener('click',()=>show('game'));document.querySelectorAll('[data-studio]').forEach(b=>b.addEventListener('click',()=>{const a=b.dataset.studio;if(a==='record')toast('RECORDING SESSION STARTED');if(a==='mix')toast('MIX SESSION OPEN');if(a==='release')toast('RELEASE WORKFLOW OPEN');}));$('parkBack')?.addEventListener('click',()=>show('game'));document.querySelectorAll('[data-park]').forEach(b=>b.addEventListener('click',()=>activityReward(b.dataset.park)));
  document.addEventListener('keydown',e=>{const t=e.target;const typing=t instanceof HTMLInputElement||t instanceof HTMLTextAreaElement||t instanceof HTMLSelectElement||t?.isContentEditable;if(typing)return;const k=e.key.length===1?e.key.toLowerCase():e.key;if(['ArrowUp','ArrowDown','ArrowLeft','ArrowRight','w','a','s','d'].includes(k)){e.preventDefault();move(k==='a'||k==='ArrowLeft'?-2:k==='d'||k==='ArrowRight'?2:0,k==='w'||k==='ArrowUp'?-2:k==='s'||k==='ArrowDown'?2:0)}});
  document.querySelectorAll('[data-key]').forEach(b=>b.onclick=()=>{const k=b.dataset.key;move(k==='ArrowLeft'?-2:k==='ArrowRight'?2:0,k==='ArrowUp'?-2:k==='ArrowDown'?2:0)});
  load();
})();
