(() => {
  const report=[];
  const pass=(name,detail)=>report.push({name,status:'PASS',detail});
  const fail=(name,detail)=>report.push({name,status:'FAIL',detail});
  const check=(name,condition,detail)=>condition?pass(name,detail):fail(name,detail);
  function run(){
    report.length=0;
    check('localStorage','localStorage' in window,'browser persistence available');
    check('game-api',!!window.TGGGame,'main game API available');check('career-api',!!window.TGGCareer,'career API available');check('content-api',!!window.TGGContent,'content API available');check('expansion-api',!!window.TGGExpansion,'city expansion API available');check('progression-api',!!window.TGGProgression,'progression API available');check('bridge-api',!!window.TGGBridge,'website bridge API available');check('inventory-api',!!window.TGGInventory&&typeof window.TGGInventory.add==='function'&&typeof window.TGGInventory.has==='function'&&typeof window.TGGInventory.remove==='function','V1.3 inventory API available');check('crew-api',!!window.TGGCrew&&typeof window.TGGCrew.recruit==='function','V1.3 crew API available');check('economy-api',!!window.TGGEconomy&&typeof window.TGGEconomy.reward==='function'&&typeof window.TGGEconomy.apply==='function','V1.3 shared economy API available');check('events-api',!!window.TGGEvents&&typeof window.TGGEvents.run==='function','V1.3 city events API available');check('avatar-api',!!window.TGGAvatar&&typeof window.TGGAvatar.get==='function'&&typeof window.TGGAvatar.save==='function'&&typeof window.TGGAvatar.open==='function','V1.5 avatar API available');check('world-sync-api',!!window.TGGWorldSync&&typeof window.TGGWorldSync.snapshot==='function'&&typeof window.TGGWorldSync.setTransport==='function'&&typeof window.TGGWorldSync.sync==='function','V1.6 world sync adapter available');
    check('chain-api',!!window.TGGChains&&typeof window.TGGChains.start==='function','mission chain API available');check('story-mission-api',!!window.TGGStoryMission&&typeof window.TGGStoryMission.act==='function'&&typeof window.TGGStoryMission.claim==='function'&&window.TGGStoryMission.mission?.id==='make-noise','V1.15 story mission API available');check('chain-ui',!!window.TGGChainUI&&typeof window.TGGChainUI.start==='function','mission chain UI API available');check('district-api',!!window.TGGDistricts&&typeof window.TGGDistricts.canEnter==='function','district progression API available');check('save-api',!!window.TGGSave&&typeof window.TGGSave.repair==='function','save validator available');
    check('screen-navigation',typeof window.TGGGame?.show==='function','screen navigation API available for deterministic subsystem routing');
    ['menu','creator','avatar','game','career','contentBoard','expansionBoard','progressionBoard','inventoryBoard','crewBoard','eventsBoard','bridge','pause','hud'].forEach(id=>check(id,!!document.getElementById(id),'required screen/control host exists'));
    ['missionBtn','saveBtn','characterBtn','avatarDone','avatarBack','rotateLeft','rotateRight','careerBtn','contentBtn','advanceContentBtn','expansionBtn','progressionBtn','inventoryBtn','crewBtn','eventsBtn','bridgeBtn','worldSyncBtn','chainBtn','missionStoryBtn'].forEach(id=>check(id,!!document.getElementById(id),'required action exists'));
    check('content-start',typeof window.TGGContent?.start==='function','content start API available');check('content-advance',typeof window.TGGContent?.advance==='function','content advance API available');
    const missions=window.TGGContent?.content?.missions||[];check('content-inventory',missions.every(m=>Array.isArray(m.requires)&&m.requires.length>=1)&&typeof window.TGGContent?.requirementsMet==='function','content missions are inventory-gated');check('expansion-run',typeof window.TGGExpansion?.run==='function','expansion run API available');check('progression-sync',typeof window.TGGProgression?.sync==='function','progression sync API available');
    const achievements=window.TGGProgression?.achievements||[];check('progression-achievements',Array.isArray(achievements)&&achievements.length>=9,'career milestone achievement catalog available');check('career-milestones',achievements.some(x=>x.id==='first-upgrade')&&achievements.some(x=>x.id==='studio-level-two'),'V1.4 career milestone achievements registered');check('career-sync',typeof window.TGGCareer?.addRep==='function'&&typeof window.TGGProgression?.sync==='function','career actions can synchronize progression without a second state store');
    check('bridge-snapshot',typeof window.TGGBridge?.snapshot==='function','bridge snapshot API available');check('district-catalog',Array.isArray(window.TGGDistricts?.districts)&&window.TGGDistricts.districts.length>=3,'district catalog available');
    const avatar=window.TGGAvatar?.get?.()||{};check('avatar-state',typeof avatar.skin==='string'&&typeof avatar.hair==='string'&&typeof avatar.top==='string'&&typeof avatar.accent==='string','V1.5 avatar state available');check('avatar-persistence',window.TGGSave?.keys?.avatar==='tgg-avatar-v1','V1.5 avatar save key registered');const worldPacket=window.TGGWorldSync?.snapshot?.()||{};check('world-sync-snapshot',worldPacket.schema==='tgg-world-sync-v1'&&worldPacket.version==='1.12.0'&&!!worldPacket.player&&!!worldPacket.avatar&&!!worldPacket.career,'V1.6 credential-free sync packet available');check('world-sync-offline-ready',window.TGGWorldSync?.status?.().status==='offline_ready','V1.6 defaults to local/offline-ready mode');const presencePacket=window.TGGWorldSync?.positionPayload?.()||{};check('world-presence-payload',!!presencePacket.position&&!!presencePacket.rotation&&!!presencePacket.activity&&presencePacket.position.space==='city_percent','V1.7 player presence payload available');check('world-presence-rpc',typeof window.TGGWorldSync?.heartbeat==='function'&&typeof window.TGGWorldSync?.presenceBundle==='function'&&typeof window.TGGWorldSync?.nextMoves==='function','V1.7 online player state bridge available');check('world-career-economy-bridge',typeof window.TGGWorldSync?.careerBundle==='function'&&typeof window.TGGWorldSync?.economyBundle==='function'&&typeof window.TGGWorldSync?.walletReconcile==='function'&&typeof window.TGGWorldSync?.readRemoteState==='function','V1.8 career/economy bridge available');check('world-inventory-equipment-bridge',typeof window.TGGWorldSync?.remoteInventory==='function'&&typeof window.TGGWorldSync?.equipRemoteItem==='function','V1.9 inventory/equipment bridge available');check('world-social-crew-bridge',typeof window.TGGWorldSync?.socialBundle==='function'&&typeof window.TGGWorldSync?.crewActivity==='function'&&typeof window.TGGWorldSync?.crewRides==='function'&&typeof window.TGGWorldSync?.crewBundle==='function'&&typeof window.TGGWorldSync?.contactOffers==='function','V1.10 social/crew discovery bridge available');check('world-mission-story-bridge',typeof window.TGGWorldSync?.creativeMissions==='function'&&typeof window.TGGWorldSync?.npcEncounters==='function'&&typeof window.TGGWorldSync?.storyControl==='function'&&typeof window.TGGWorldSync?.memoryHistory==='function'&&typeof window.TGGWorldSync?.locationBundle==='function'&&typeof window.TGGWorldSync?.missionStoryBundle==='function','V1.11 mission/story discovery bridge available');check('world-property-vehicle-bridge',typeof window.TGGWorldSync?.propertyMarket==='function'&&typeof window.TGGWorldSync?.propertyUpgrades==='function'&&typeof window.TGGWorldSync?.vehicleProgression==='function'&&typeof window.TGGWorldSync?.vehicleBundle==='function'&&typeof window.TGGWorldSync?.worldAssetsBundle==='function','V1.12 property/vehicle discovery bridge available');
        const business=window.TGGBusiness;check('business-api',!!business&&typeof business.open==='function'&&typeof business.select==='function'&&typeof business.sync==='function','V1.13 business discovery API available');check('business-catalog',Array.isArray(business?.catalog)&&business.catalog.length>=4,'business discovery catalog available');check('business-persistence',Array.isArray(business?.state?.discovered)&&typeof business?.save==='function'&&typeof business?.load==='function','business discovery persistence available');check('business-screen',!!document.getElementById('businessBoard')&&!!document.getElementById('businessBtn'),'business screen and city control available');check('business-assets-loader',typeof business?.loadAssets==='function','V1.14 world asset loader available');check('business-assets-state',!!business?.state?.assets&&typeof business.state.assets==='object','V1.14 property/vehicle asset state available');check('city-assets-hotspot',!!document.getElementById('cityAssetsBtn'),'V1.14 city world-assets hotspot available');check('business-styles',!!document.querySelector('.business-grid'),'V1.14 business hub markup available');
const inventory=window.TGGInventory?.catalog||[];check('inventory-catalog',inventory.length>=4&&inventory.some(x=>x.id==='beat-pack'),'inventory catalog available');
    check('crew-catalog',Array.isArray(window.TGGCrew?.catalog)&&window.TGGCrew.catalog.length>=3,'crew catalog available');check('crew-bonus',typeof window.TGGCrew?.bonus==='function','crew bonus API available');
    const events=window.TGGEvents?.events||[];check('events-catalog',Array.isArray(events)&&events.length>=3,'city events catalog available');check('events-run',typeof window.TGGEvents?.run==='function','city events run API available');check('events-inventory',events.every(e=>Array.isArray(e.requires)&&e.requires.length>=1)&&typeof window.TGGEvents?.requirementsMet==='function','city events are inventory-gated');
    const economy=window.TGGEconomy?.reward?.({cash:100,xp:20,rep:5});check('economy-reward-shape',!!economy&&economy.cash>=100&&economy.xp>=20&&economy.rep>=5&&!!economy.crew,'shared economy reward normalization available');
    check('story-mission-ui',!!document.getElementById('missionStoryStatus')&&!!document.getElementById('missionStoryBtn'),'V1.15 story mission UI available');const integrity=window.TGGV12Integrity?.run?.();check('v12-integrity',!!integrity?.passed,'V1.2 integrity gate passes');
    const bad=report.filter(x=>x.status==='FAIL');window.TGGQA={report,passed:bad.length===0,repair(){window.TGGSave?.repair?.();return !!document.getElementById('hud')&&!!window.TGGGame&&!!window.TGGProgression&&!!window.TGGChains&&!!window.TGGDistricts&&!!window.TGGSave&&!!window.TGGInventory&&!!window.TGGCrew&&!!window.TGGEconomy&&!!window.TGGEvents&&!!window.TGGAvatar&&!!window.TGGWorldSync}};return window.TGGQA;
  }
  window.TGGQA={run};
})();
