(() => {
  const report=[];
  const pass=(name,detail)=>report.push({name,status:'PASS',detail});
  const fail=(name,detail)=>report.push({name,status:'FAIL',detail});
  const check=(name,condition,detail)=>condition?pass(name,detail):fail(name,detail);
  function run(){
    report.length=0;
    check('localStorage','localStorage' in window,'browser persistence available');
    check('game-api',!!window.TGGGame,'main game API available');check('career-api',!!window.TGGCareer,'career API available');check('content-api',!!window.TGGContent,'content API available');check('expansion-api',!!window.TGGExpansion,'city expansion API available');check('progression-api',!!window.TGGProgression,'progression API available');check('bridge-api',!!window.TGGBridge,'website bridge API available');check('inventory-api',!!window.TGGInventory&&typeof window.TGGInventory.add==='function'&&typeof window.TGGInventory.has==='function'&&typeof window.TGGInventory.remove==='function','V1.3 inventory API available');check('crew-api',!!window.TGGCrew&&typeof window.TGGCrew.recruit==='function','V1.3 crew API available');check('economy-api',!!window.TGGEconomy&&typeof window.TGGEconomy.reward==='function'&&typeof window.TGGEconomy.apply==='function','V1.3 shared economy API available');check('events-api',!!window.TGGEvents&&typeof window.TGGEvents.run==='function','V1.3 city events API available');check('avatar-api',!!window.TGGAvatar&&typeof window.TGGAvatar.get==='function'&&typeof window.TGGAvatar.save==='function'&&typeof window.TGGAvatar.open==='function','V1.5 avatar API available');
    check('chain-api',!!window.TGGChains&&typeof window.TGGChains.start==='function','mission chain API available');check('chain-ui',!!window.TGGChainUI&&typeof window.TGGChainUI.start==='function','mission chain UI API available');check('district-api',!!window.TGGDistricts&&typeof window.TGGDistricts.canEnter==='function','district progression API available');check('save-api',!!window.TGGSave&&typeof window.TGGSave.repair==='function','save validator available');
    check('screen-navigation',typeof window.TGGGame?.show==='function','screen navigation API available for deterministic subsystem routing');
    ['menu','creator','avatar','game','career','contentBoard','expansionBoard','progressionBoard','inventoryBoard','crewBoard','eventsBoard','bridge','pause','hud'].forEach(id=>check(id,!!document.getElementById(id),'required screen/control host exists'));
    ['missionBtn','saveBtn','characterBtn','avatarDone','avatarBack','rotateLeft','rotateRight','careerBtn','contentBtn','advanceContentBtn','expansionBtn','progressionBtn','inventoryBtn','crewBtn','eventsBtn','bridgeBtn','chainBtn'].forEach(id=>check(id,!!document.getElementById(id),'required action exists'));
    check('content-start',typeof window.TGGContent?.start==='function','content start API available');check('content-advance',typeof window.TGGContent?.advance==='function','content advance API available');
    const missions=window.TGGContent?.content?.missions||[];check('content-inventory',missions.every(m=>Array.isArray(m.requires)&&m.requires.length>=1)&&typeof window.TGGContent?.requirementsMet==='function','content missions are inventory-gated');check('expansion-run',typeof window.TGGExpansion?.run==='function','expansion run API available');check('progression-sync',typeof window.TGGProgression?.sync==='function','progression sync API available');
    const achievements=window.TGGProgression?.achievements||[];check('progression-achievements',Array.isArray(achievements)&&achievements.length>=9,'career milestone achievement catalog available');check('career-milestones',achievements.some(x=>x.id==='first-upgrade')&&achievements.some(x=>x.id==='studio-level-two'),'V1.4 career milestone achievements registered');check('career-sync',typeof window.TGGCareer?.addRep==='function'&&typeof window.TGGProgression?.sync==='function','career actions can synchronize progression without a second state store');
    check('bridge-snapshot',typeof window.TGGBridge?.snapshot==='function','bridge snapshot API available');check('district-catalog',Array.isArray(window.TGGDistricts?.districts)&&window.TGGDistricts.districts.length>=3,'district catalog available');
    const avatar=window.TGGAvatar?.get?.()||{};check('avatar-state',typeof avatar.skin==='string'&&typeof avatar.hair==='string'&&typeof avatar.top==='string'&&typeof avatar.accent==='string','V1.5 avatar state available');check('avatar-persistence',window.TGGSave?.keys?.avatar==='tgg-avatar-v1','V1.5 avatar save key registered');
    const inventory=window.TGGInventory?.catalog||[];check('inventory-catalog',inventory.length>=4&&inventory.some(x=>x.id==='beat-pack'),'inventory catalog available');
    check('crew-catalog',Array.isArray(window.TGGCrew?.catalog)&&window.TGGCrew.catalog.length>=3,'crew catalog available');check('crew-bonus',typeof window.TGGCrew?.bonus==='function','crew bonus API available');
    const events=window.TGGEvents?.events||[];check('events-catalog',Array.isArray(events)&&events.length>=3,'city events catalog available');check('events-run',typeof window.TGGEvents?.run==='function','city events run API available');check('events-inventory',events.every(e=>Array.isArray(e.requires)&&e.requires.length>=1)&&typeof window.TGGEvents?.requirementsMet==='function','city events are inventory-gated');
    const economy=window.TGGEconomy?.reward?.({cash:100,xp:20,rep:5});check('economy-reward-shape',!!economy&&economy.cash>=100&&economy.xp>=20&&economy.rep>=5&&!!economy.crew,'shared economy reward normalization available');
    const integrity=window.TGGV12Integrity?.run?.();check('v12-integrity',!!integrity?.passed,'V1.2 integrity gate passes');
    const bad=report.filter(x=>x.status==='FAIL');window.TGGQA={report,passed:bad.length===0,repair(){window.TGGSave?.repair?.();return !!document.getElementById('hud')&&!!window.TGGGame&&!!window.TGGProgression&&!!window.TGGChains&&!!window.TGGDistricts&&!!window.TGGSave&&!!window.TGGInventory&&!!window.TGGCrew&&!!window.TGGEconomy&&!!window.TGGEvents&&!!window.TGGAvatar}};return window.TGGQA;
  }
  window.TGGQA={run};
})();
