(() => {
  const checks=[]; const test=(name,pass,detail='')=>checks.push({name,pass:!!pass,detail});
  function run(){
    checks.length=0;
    test('game api',!!window.TGGGame);
    test('v2 walking api',typeof window.TGGGame?.getWalkingState==='function'&&typeof window.TGGGame?.setWalkKey==='function');
    const walkTune=window.TGGGame?.getWalkTuning?.()||{};test('v2 walking tune',Number(walkTune.walkSpeed)>0&&Number(walkTune.sprintSpeed)>Number(walkTune.walkSpeed));
    test('v2 player dynamics',typeof window.TGG3D?.setPlayerDynamics==='function'&&typeof window.TGG3D?.getPlayerDynamics==='function');
    const carSpawn=window.TGG3D?.getCarPercent?.();
    test('v204 car position api',Number.isFinite(carSpawn?.x)&&Number.isFinite(carSpawn?.y));
    test('v204 starter car safe spawn',!!carSpawn&&window.TGG3D?.canMovePercent?.(carSpawn.x,carSpawn.y,true)===true);
    test('v204 drive input api',typeof window.TGGGame?.driveVehicle==='function'&&typeof window.TGGGame?.setDriveKey==='function');
    test('v205 car recovery api',typeof window.TGGGame?.recoverVehicle==='function');
    test('v205 reset car control',!!document.getElementById('recoverCarBtn'));
    const driveState=window.TGGGame?.getDrivingState?.()||{};
    test('v206 boost runtime',typeof driveState.boostEnergy==='number'&&driveState.boostEnergy>=0&&driveState.boostEnergy<=100);
    test('v206 boost hud',!!document.getElementById('boostValue')&&!!document.getElementById('boostFill'));
    test('v206 unified job nav',typeof window.TGGStreetContacts?.closest==='function'&&typeof window.TGGStreetContacts?.focusNearest==='function'&&typeof window.TGGStreetContacts?.getNavTarget==='function');
    test('v207 boost flames',Array.isArray(window.TGG3D?.car?.userData?.boostFlames)&&window.TGG3D.car.userData.boostFlames.length===2);
    test('v207 sport car visuals',!!window.TGG3D?.car?.userData?.spoiler&&!!window.TGG3D?.car?.userData?.underGlow&&!!window.TGG3D?.car?.userData?.boostGlow);
    test('v208 street life api',!!window.TGGStreetLife&&typeof window.TGGStreetLife.status==='function'&&typeof window.TGGStreetLife.relationshipLine==='function');
    test('v208 pedestrian horn reaction',typeof window.TGG3D?.reactToHorn==='function');
    test('v208 contact object bridge',typeof window.TGGStreetContacts?.getObject==='function');
    test('v208 mission depth',window.TGGContent?.content?.missions?.every(m=>Number(m.goal)>=2)===true);
    test('v208 street life css',!!document.querySelector('link[href*="v208-street-life.css"]'));
    test('v209 city action api',!!window.TGGCityAction&&typeof window.TGGCityAction.handleImpact==='function'&&typeof window.TGGCityAction.showScene==='function');
    test('v209 traffic bridge',typeof window.TGG3D?.nearestTraffic==='function'&&typeof window.TGGGame?.vehicleImpact==='function');
    test('v209 mission handoff',typeof window.TGGStreetContacts?.focusMission==='function'&&typeof window.TGGStreetContacts?.contactForMission==='function');
    test('v209 city action css',!!document.querySelector('link[href*="v209-city-action.css"]'));
    const cityDepth=window.TGGCityDepth?.status?.()||{};
    test('v210 city depth api',!!window.TGGCityDepth&&typeof window.TGGCityDepth.boot==='function');
    test('v210 traffic lights',Number(cityDepth.trafficLights)>=8);
    test('v210 billboards',Number(cityDepth.billboards)>=3);
    const living=window.TGGLivingTraffic?.status?.()||{};
    test('v211 living traffic api',!!window.TGGLivingTraffic&&typeof window.TGGLivingTraffic.updateTraffic==='function'&&typeof window.TGGLivingTraffic.signal==='function');
    test('v211 traffic control bridge',typeof window.TGG3D?.setTrafficSpeed==='function'&&Array.isArray(window.TGG3D?.traffic));
    test('v211 signal bridge',typeof window.TGGCityDepth?.signalForAxis==='function');
    test('v211 traffic hud',!!document.getElementById('livingTrafficHud'));
    test('v211 traffic state',Number(living?.traffic?.count)>=4);
    const mega=window.TGGV212?.status?.()||{};
    test('v212 mega api',!!window.TGGV212&&typeof window.TGGV212.repairCar==='function'&&typeof window.TGGV212.damage==='function');
    test('v212 100 layers',Array.isArray(window.TGGV212?.layers)&&window.TGGV212.layers.length===100);
    test('v212 condition state',Number(mega.condition)>=0&&Number(mega.condition)<=100);
    test('v212 repair control',!!document.getElementById('repairCarBtn'));
    test('v212 drive hud',!!document.getElementById('megaDriveHud'));
    test('v212 help overlay',!!document.getElementById('megaHelpBtn')&&!!document.getElementById('megaHelpPanel'));
    test('v212 mega css',!!document.querySelector('link[href*="v212-mega-100.css"]'));
    const polish=window.TGGV213?.status?.()||{};
    test('v213 world polish api',!!window.TGGV213&&typeof window.TGGV213.boot==='function'&&typeof window.TGGV213.impactSparks==='function');
    test('v213 100 layers',Array.isArray(window.TGGV213?.layers)&&window.TGGV213.layers.length===100);
    test('v213 world props',Number(polish.props)>=20);
    test('v213 traffic population',Number(polish.extraTraffic)>=4&&Number(polish.trafficTotal)>=10);
    test('v213 pedestrian population',Number(polish.extraPedestrians)>=4&&Number(polish.pedestrianTotal)>=10);
    test('v213 world polish css',!!document.querySelector('link[href*="v213-world-polish.css"]'));
    const harden=window.TGGV214?.status?.()||{};
    test('v214 hardening api',!!window.TGGV214&&typeof window.TGGV214.snapshot==='function'&&typeof window.TGGV214.guardPlayerState==='function');
    test('v214 100 layers',Array.isArray(window.TGGV214?.layers)&&window.TGGV214.layers.length===100);
    test('v214 diagnostics control',!!document.getElementById('v214DiagBtn')&&!!document.getElementById('v214DiagPanel'));
    test('v214 fullscreen control',!!document.getElementById('v214FullBtn'));
    test('v214 storage health',harden.storageHealthy!==false);
    test('v214 hardening css',!!document.querySelector('link[href*="v214-playtest-hardening.css"]'));
    const depth=window.TGGV215?.status?.()||{};
    test('v215 character mission api',!!window.TGGV215&&typeof window.TGGV215.setEmote==='function'&&typeof window.TGGV215.scoreMission==='function');
    test('v215 100 layers',Array.isArray(window.TGGV215?.layers)&&window.TGGV215.layers.length===100);
    test('v215 emote control',!!document.getElementById('v215EmoteBtn'));
    test('v215 mission hud',!!document.getElementById('v215MissionHud'));
    test('v215 mission score card',!!document.getElementById('v215MissionCard'));
    test('v215 character mission css',!!document.querySelector('link[href*="v215-character-mission.css"]'));
    const models=window.TGGV216?.status?.()||{};
    test('v216 model polish api',!!window.TGGV216&&typeof window.TGGV216.decorateHuman==='function'&&typeof window.TGGV216.addCarDetail==='function');
    test('v216 100 layers',Array.isArray(window.TGGV216?.layers)&&window.TGGV216.layers.length===100);
    test('v216 model polish css',!!document.querySelector('link[href*="v216-model-polish.css"]'));
    test('v216 model population api',typeof window.TGGV216?.decoratePopulation==='function');
    const interiors=window.TGGV217?.status?.()||{};
    test('v217 interior depth api',!!window.TGGV217&&typeof window.TGGV217.startActivity==='function'&&typeof window.TGGV217.decorateActive==='function');
    test('v217 100 layers',Array.isArray(window.TGGV217?.layers)&&window.TGGV217.layers.length===100);
    test('v217 interior overlay',!!document.getElementById('v217InteriorOverlay'));
    test('v217 interior depth css',!!document.querySelector('link[href*="v217-interior-depth.css"]'));
    const missionActions=window.TGGV218?.status?.()||{};
    test('v218 mission actions api',!!window.TGGV218&&typeof window.TGGV218.enterObjective==='function'&&typeof window.TGGV218.performStep==='function');
    test('v218 100 layers',Array.isArray(window.TGGV218?.layers)&&window.TGGV218.layers.length===100);
    test('v218 mission action hud',!!document.getElementById('v218MissionAction')&&!!document.getElementById('v218ActionBtn'));
    test('v218 mission actions css',!!document.querySelector('link[href*="v218-mission-actions.css"]'));
    test('v218 world objective hook',String(window.TGGWorldGameplay?.performObjective||'').length>0);
    const cityInteractions=window.TGGV219?.status?.()||{};
    test('v219 city interactions api',!!window.TGGV219&&typeof window.TGGV219.interactNearest==='function'&&typeof window.TGGV219.fastTravel==='function');
    test('v219 100 layers',Array.isArray(window.TGGV219?.layers)&&window.TGGV219.layers.length===100);
    test('v219 city interaction props',Number(cityInteractions.props)>=9);
    test('v219 city interaction hud',!!document.getElementById('v219NearHud')&&!!document.getElementById('v219Panel'));
    test('v219 city interactions css',!!document.querySelector('link[href*="v219-city-interactions.css"]'));
    const worldEvents=window.TGGV220?.status?.()||{};
    test('v220 world events api',!!window.TGGV220&&typeof window.TGGV220.openPanel==='function'&&typeof window.TGGV220.completeEvent==='function');
    test('v220 100 layers',Array.isArray(window.TGGV220?.layers)&&window.TGGV220.layers.length===100);
    test('v220 event rotation',!!worldEvents.activeEventId&&Number(worldEvents.secondsLeft)>=0);
    test('v220 event hud',!!document.getElementById('v220EventHud')&&!!document.getElementById('v220EventPanel'));
    test('v220 world events css',!!document.querySelector('link[href*="v220-world-events.css"]'));
    const battle=window.TGGV221?.status?.()||{};
    test('v221 rap battle api',!!window.TGGV221&&typeof window.TGGV221.openBattle==='function'&&typeof window.TGGV221.dropBar==='function');
    test('v221 100 layers',Array.isArray(window.TGGV221?.layers)&&window.TGGV221.layers.length===100);
    test('v221 battle HUD',!!document.getElementById('v221BattlePanel')&&!!document.getElementById('v221Drop'));
    test('v221 event handoff',typeof window.TGGV221?.shouldHandleEvent==='function');
    test('v221 rap battle css',!!document.querySelector('link[href*="v221-rap-battle.css"]'));
    const concert=window.TGGV222?.status?.()||{};
    test('v222 concert api',!!window.TGGV222&&typeof window.TGGV222.openShow==='function'&&typeof window.TGGV222.performHit==='function');
    test('v222 100 layers',Array.isArray(window.TGGV222?.layers)&&window.TGGV222.layers.length===100);
    test('v222 venue HUD',!!document.getElementById('v222ShowPanel')&&!!document.getElementById('v222Perform'));
    test('v222 cooldown api',typeof window.TGGV222?.cooldownLeft==='function');
    test('v222 concert css',!!document.querySelector('link[href*="v222-concert.css"]'));
    const story=window.TGGV223?.status?.()||{};
    test('v223 career story api',!!window.TGGV223&&typeof window.TGGV223.openPhone==='function'&&typeof window.TGGV223.activeChapter==='function');
    test('v223 100 layers',Array.isArray(window.TGGV223?.layers)&&window.TGGV223.layers.length===100);
    test('v223 six chapters',Array.isArray(window.TGGV223?.chapters)&&window.TGGV223.chapters.length===6);
    test('v223 phone ui',!!document.getElementById('v223PhoneBtn')&&!!document.getElementById('v223PhonePanel'));
    test('v223 chapter status',Number(story.chapter)>=1&&Number(story.chapter)<=6);
    test('v223 career story css',!!document.querySelector('link[href*="v223-career-story.css"]'));
    const crewHQ=window.TGGV224?.status?.()||{};
    test('v224 crew HQ api',!!window.TGGV224&&typeof window.TGGV224.startContract==='function'&&typeof window.TGGV224.chemistry==='function');
    test('v224 100 layers',Array.isArray(window.TGGV224?.layers)&&window.TGGV224.layers.length===100);
    test('v224 crew HQ UI',!!document.getElementById('v224CrewPanel')&&!!document.getElementById('v224NearHud'));
    test('v224 crew chemistry range',Number(crewHQ.chemistry)>=0&&Number(crewHQ.chemistry)<=100);
    test('v224 crew HQ css',!!document.querySelector('link[href*="v224-crew-hq.css"]'));
    const rivals=window.TGGV225?.status?.()||{};
    test('v225 rival core api',!!window.TGGV225Core&&typeof window.TGGV225Core.applyChoice==='function'&&typeof window.TGGV225Core.relationshipTier==='function');
    test('v225 rival crew api',!!window.TGGV225&&typeof window.TGGV225.choose==='function'&&typeof window.TGGV225.openEncounter==='function');
    test('v225 100 layers',Array.isArray(window.TGGV225?.layers)&&window.TGGV225.layers.length===100);
    test('v225 rival crew ui',!!document.getElementById('v225RivalPanel')&&!!document.getElementById('v225RivalHud'));
    test('v225 rival state range',Number(rivals.rivalry)>=0&&Number(rivals.rivalry)<=100&&Number(rivals.respect)>=0&&Number(rivals.respect)<=100);
    test('v225 rival crew css',!!document.querySelector('link[href*="v225-rival-crews.css"]'));
    const assets=window.TGGV226?.status?.()||{};
    test('v226 asset core api',!!window.TGGV226Core&&typeof window.TGGV226Core.isSupportedModelUrl==='function'&&typeof window.TGGV226Core.nextState==='function');
    test('v226 asset loader api',!!window.TGGV226&&typeof window.TGGV226.configure==='function'&&typeof window.TGGV226.loadModel==='function');
    test('v226 100 layers',Array.isArray(window.TGGV226?.layers)&&window.TGGV226.layers.length===100);
    test('v226 procedural fallback',assets.fallbackMode==='procedural'&&assets.usingFallback!==false);
    test('v226 asset HUD',!!document.getElementById('v226AssetHud'));
    test('v226 asset loader css',!!document.querySelector('link[href*="v226-asset-loader.css"]'));
    const forge=window.TGGV227?.status?.()||{};
    test('v227 forge core api',!!window.TGGV227Core&&typeof window.TGGV227Core.normalizePreset==='function'&&typeof window.TGGV227Core.applyMorph==='function');
    test('v227 forge api',!!window.TGGV227&&typeof window.TGGV227.rebuild==='function'&&typeof window.TGGV227.applyPreset==='function');
    test('v227 100 layers',Array.isArray(window.TGGV227?.layers)&&window.TGGV227.layers.length===100);
    test('v227 native forge mode',forge.mode==='native-forge'&&forge.preset==='street');
    test('v227 forge UI',!!document.getElementById('v227ForgeBtn')&&!!document.getElementById('v227ForgePanel'));
    test('v227 forge css',!!document.querySelector('link[href*="v227-forge.css"]'));
    const vehicleForge=window.TGGV228?.status?.()||{};
    test('v228 vehicle core api',!!window.TGGV228Core&&typeof window.TGGV228Core.normalize==='function'&&typeof window.TGGV228Core.applyTuning==='function');
    test('v228 vehicle forge api',!!window.TGGV228&&typeof window.TGGV228.rebuild==='function'&&typeof window.TGGV228.applyPreset==='function');
    test('v228 100 layers',Array.isArray(window.TGGV228?.layers)&&window.TGGV228.layers.length===100);
    test('v228 native vehicle mode',vehicleForge.mode==='native-vehicle-forge'&&vehicleForge.preset==='street');
    test('v228 vehicle forge UI',!!document.getElementById('v228ForgeBtn')&&!!document.getElementById('v228ForgePanel'));
    test('v228 vehicle forge css',!!document.querySelector('link[href*="v228-vehicle-forge.css"]'));
    const worldForge=window.TGGV229?.status?.()||{};
    test('v229 world core api',!!window.TGGV229Core&&typeof window.TGGV229Core.preset==='function'&&typeof window.TGGV229Core.modulesFor==='function');
    test('v229 world forge api',!!window.TGGV229&&typeof window.TGGV229.rebuild==='function'&&typeof window.TGGV229.setEnabled==='function');
    test('v229 100 layers',Array.isArray(window.TGGV229?.layers)&&window.TGGV229.layers.length===100);
    test('v229 native world mode',worldForge.mode==='native-world-forge'&&worldForge.enabled===true);
    test('v229 world forge UI',!!document.getElementById('v229ForgeBtn')&&!!document.getElementById('v229ForgePanel'));
    test('v229 world forge css',!!document.querySelector('link[href*="v229-world-forge.css"]'));
    const interiorForge=window.TGGV230?.status?.()||{};
    test('v230 interior core api',!!window.TGGV230Core&&typeof window.TGGV230Core.room==='function'&&typeof window.TGGV230Core.canWalk==='function');
    test('v230 interior forge api',!!window.TGGV230&&typeof window.TGGV230.enter==='function'&&typeof window.TGGV230.exit==='function');
    test('v230 100 layers',Array.isArray(window.TGGV230?.layers)&&window.TGGV230.layers.length===100);
    test('v230 native interior mode',interiorForge.mode==='native-interior-forge');
    test('v230 interior HUD',!!document.getElementById('v230InteriorHud'));
    test('v230 interior forge css',!!document.querySelector('link[href*="v230-interior-forge.css"]'));
    const lightForge=window.TGGV231?.status?.()||{};
    test('v231 lighting core api',!!window.TGGV231Core&&typeof window.TGGV231Core.mood==='function'&&typeof window.TGGV231Core.material==='function');
    test('v231 lighting forge api',!!window.TGGV231&&typeof window.TGGV231.applyMood==='function'&&typeof window.TGGV231.regrade==='function');
    test('v231 100 layers',Array.isArray(window.TGGV231?.layers)&&window.TGGV231.layers.length===100);
    test('v231 native lighting mode',lightForge.mode==='native-lighting-forge'&&lightForge.mood==='night');
    test('v231 lighting HUD',!!document.getElementById('v231ForgeHud')&&!!document.getElementById('v231ForgePanel'));
    test('v231 lighting forge css',!!document.querySelector('link[href*="v231-lighting-forge.css"]'));
    const animForge=window.TGGV232?.status?.()||{};
    test('v232 animation core api',!!window.TGGV232Core&&typeof window.TGGV232Core.clip==='function'&&typeof window.TGGV232Core.blend==='function');
    test('v232 animation forge api',!!window.TGGV232&&typeof window.TGGV232.play==='function'&&typeof window.TGGV232.clear==='function');
    test('v232 100 layers',Array.isArray(window.TGGV232?.layers)&&window.TGGV232.layers.length===100);
    test('v232 native animation mode',animForge.mode==='native-animation-forge'&&animForge.enabled===true);
    test('v232 animation HUD',!!document.getElementById('v232ForgeHud')&&!!document.getElementById('v232ForgePanel'));
    test('v232 animation forge css',!!document.querySelector('link[href*="v232-animation-forge.css"]'));
    const weatherForge=window.TGGV233?.status?.()||{};
    test('v233 weather core api',!!window.TGGV233Core&&typeof window.TGGV233Core.preset==='function'&&typeof window.TGGV233Core.particleBudget==='function');
    test('v233 weather forge api',!!window.TGGV233&&typeof window.TGGV233.applyPreset==='function'&&typeof window.TGGV233.restore==='function');
    test('v233 100 layers',Array.isArray(window.TGGV233?.layers)&&window.TGGV233.layers.length===100);
    test('v233 native weather mode',weatherForge.mode==='native-weather-forge'&&weatherForge.enabled===true);
    test('v233 weather HUD',!!document.getElementById('v233ForgeHud')&&!!document.getElementById('v233ForgePanel'));
    test('v233 weather forge css',!!document.querySelector('link[href*="v233-weather-forge.css"]'));
    const cameraForge=window.TGGV234?.status?.()||{};
    test('v234 camera core api',!!window.TGGV234Core&&typeof window.TGGV234Core.preset==='function'&&typeof window.TGGV234Core.blend==='function');
    test('v234 camera forge api',!!window.TGGV234&&typeof window.TGGV234.applyPreset==='function'&&typeof window.TGGV234.pulse==='function');
    test('v234 100 layers',Array.isArray(window.TGGV234?.layers)&&window.TGGV234.layers.length===100);
    test('v234 native camera mode',cameraForge.mode==='native-camera-forge'&&cameraForge.enabled===true);
    test('v234 camera HUD',!!document.getElementById('v234ForgeHud')&&!!document.getElementById('v234ForgePanel'));
    test('v234 camera forge css',!!document.querySelector('link[href*="v234-camera-forge.css"]'));
    const faceForge=window.TGGV235?.status?.()||{};
    test('v235 face core api',!!window.TGGV235Core&&typeof window.TGGV235Core.expression==='function'&&typeof window.TGGV235Core.blend==='function');
    test('v235 face forge api',!!window.TGGV235&&typeof window.TGGV235.applyExpression==='function'&&typeof window.TGGV235.restore==='function');
    test('v235 100 layers',Array.isArray(window.TGGV235?.layers)&&window.TGGV235.layers.length===100);
    test('v235 native face mode',faceForge.mode==='native-face-forge'&&faceForge.enabled===true);
    test('v235 face HUD',!!document.getElementById('v235ForgeHud')&&!!document.getElementById('v235ForgePanel'));
    test('v235 face forge css',!!document.querySelector('link[href*="v235-face-forge.css"]'));
    const npcForgeV236=window.TGGV236?.status?.()||{};
    test('v236 npc core api',!!window.TGGV236Core&&typeof window.TGGV236Core.variant==='function'&&typeof window.TGGV236Core.lod==='function');
    test('v236 npc forge api',!!window.TGGV236&&typeof window.TGGV236.refresh==='function'&&typeof window.TGGV236.restore==='function');
    test('v236 100 layers',Array.isArray(window.TGGV236?.layers)&&window.TGGV236.layers.length===100);
    test('v236 native npc mode',npcForgeV236.mode==='native-npc-forge'&&npcForgeV236.enabled===true);
    test('v236 NPC HUD',!!document.getElementById('v236ForgeHud')&&!!document.getElementById('v236ForgePanel'));
    test('v236 NPC forge css',!!document.querySelector('link[href*="v236-npc-forge.css"]'));
    const audioForgeV237=window.TGGV237?.status?.()||{};
    test('v237 audio core api',!!window.TGGV237Core&&typeof window.TGGV237Core.ambience==='function'&&typeof window.TGGV237Core.cue==='function'&&typeof window.TGGV237Core.normalize==='function');
    test('v237 audio forge api',!!window.TGGV237&&typeof window.TGGV237.start==='function'&&typeof window.TGGV237.stop==='function'&&typeof window.TGGV237.playCue==='function');
    test('v237 100 layers',Array.isArray(window.TGGV237?.layers)&&window.TGGV237.layers.length===100);
    test('v237 native audio mode',audioForgeV237.mode==='native-audio-forge');
    test('v237 audio HUD',!!document.getElementById('v237ForgeHud')&&!!document.getElementById('v237ForgePanel'));
    test('v237 audio forge css',!!document.querySelector('link[href*="v237-audio-forge.css"]'));
    const cameraForgeV234=window.TGGV234?.status?.()||{};
    test('v234 camera core api',!!window.TGGV234Core&&typeof window.TGGV234Core.preset==='function'&&typeof window.TGGV234Core.blend==='function');
    test('v234 camera forge api',!!window.TGGV234&&typeof window.TGGV234.applyPreset==='function'&&typeof window.TGGV234.pulse==='function'&&typeof window.TGGV234.togglePhoto==='function');
    test('v234 100 layers',Array.isArray(window.TGGV234?.layers)&&window.TGGV234.layers.length===100);
    test('v234 native camera mode',cameraForgeV234.mode==='native-camera-forge'&&cameraForgeV234.enabled===true);
    test('v234 camera HUD',!!document.getElementById('v234ForgeHud')&&!!document.getElementById('v234ForgePanel'));
    test('v234 camera forge css',!!document.querySelector('link[href*="v234-camera-forge.css"]'));
    test('v2 final runtime',window.TGGFinalBuild?.version==='V2.37 TGG AUDIO + AMBIENCE FORGE 100');
    test('v2 movement hud',!!document.getElementById('playerMoveHud')&&!!document.getElementById('walkModeValue')&&!!document.getElementById('walkSpeedValue'));
    test('v2 sprint control',!!document.getElementById('sprintBtn'));test('v202 world gameplay',!!window.TGGWorldGameplay&&typeof window.TGGWorldGameplay.getNavTarget==='function'&&typeof window.TGGWorldGameplay.performObjective==='function');test('v202 world objective hud',!!document.getElementById('worldObjective'));test('v203 street contacts',!!window.TGGStreetContacts&&Array.isArray(window.TGGStreetContacts.contacts)&&window.TGGStreetContacts.contacts.length>=3&&typeof window.TGGStreetContacts.startContact==='function');test('v203 contact hud',!!document.getElementById('streetContactCard'));test('career api',!!window.TGGCareer);test('content api',!!window.TGGContent);test('expansion api',!!window.TGGExpansion);test('progression api',!!window.TGGProgression);test('bridge api',!!window.TGGBridge);test('chain api',!!window.TGGChains);test('district api',!!window.TGGDistricts);test('save api',!!window.TGGSave);test('inventory api',!!window.TGGInventory);test('crew api',!!window.TGGCrew);test('events api',!!window.TGGEvents);test('economy api',!!window.TGGEconomy&&typeof window.TGGEconomy.apply==='function');test('avatar api',!!window.TGGAvatar&&typeof window.TGGAvatar.get==='function'&&typeof window.TGGAvatar.save==='function');test('world sync api',!!window.TGGWorldSync&&typeof window.TGGWorldSync.snapshot==='function'&&typeof window.TGGWorldSync.setTransport==='function'&&typeof window.TGGWorldSync.sync==='function');
    ['menu','creator','avatar','game','career','contentBoard','expansionBoard','progressionBoard','inventoryBoard','crewBoard','eventsBoard','bridge','pause','hud'].forEach(id=>test('dom:'+id,!!document.getElementById(id)));
    ['newGame','continueGame','startGame','avatarStart','characterBtn','avatarDone','avatarBack','rotateLeft','rotateRight','missionBtn','careerBtn','contentBtn','advanceContentBtn','expansionBtn','progressionBtn','inventoryBtn','crewBtn','eventsBtn','bridgeBtn','worldSyncBtn','chainBtn','saveBtn','pauseBtn','resumeBtn','menuBtn','recordBtn','mixtapeBtn','upgradeBtn'].forEach(id=>test('control:'+id,!!document.getElementById(id)));
    test('local storage',typeof localStorage!=='undefined');const av=window.TGGAvatar?.get?.()||{};test('avatar state',typeof av.skin==='string'&&typeof av.hair==='string'&&typeof av.top==='string'&&typeof av.accent==='string');test('avatar save integration',window.TGGSave?.keys?.avatar==='tgg-avatar-v1');const ws=window.TGGWorldSync?.snapshot?.()||{};test('world sync packet',ws.schema==='tgg-world-sync-v1'&&ws.version==='1.12.0'&&!!ws.player&&!!ws.avatar&&!!ws.career);test('world sync offline default',window.TGGWorldSync?.status?.().status==='offline_ready');const wp=window.TGGWorldSync?.positionPayload?.()||{};test('world presence packet',!!wp.position&&!!wp.rotation&&!!wp.activity&&wp.position.space==='city_percent');test('world presence bridge',typeof window.TGGWorldSync?.heartbeat==='function'&&typeof window.TGGWorldSync?.presenceBundle==='function'&&typeof window.TGGWorldSync?.nextMoves==='function');test('world career economy bridge',typeof window.TGGWorldSync?.careerBundle==='function'&&typeof window.TGGWorldSync?.economyBundle==='function'&&typeof window.TGGWorldSync?.walletReconcile==='function'&&typeof window.TGGWorldSync?.readRemoteState==='function');test('world inventory equipment bridge',typeof window.TGGWorldSync?.remoteInventory==='function'&&typeof window.TGGWorldSync?.equipRemoteItem==='function');test('world social crew bridge',typeof window.TGGWorldSync?.socialBundle==='function'&&typeof window.TGGWorldSync?.crewActivity==='function'&&typeof window.TGGWorldSync?.crewRides==='function'&&typeof window.TGGWorldSync?.crewBundle==='function'&&typeof window.TGGWorldSync?.contactOffers==='function');test('world mission story bridge',typeof window.TGGWorldSync?.creativeMissions==='function'&&typeof window.TGGWorldSync?.npcEncounters==='function'&&typeof window.TGGWorldSync?.storyControl==='function'&&typeof window.TGGWorldSync?.memoryHistory==='function'&&typeof window.TGGWorldSync?.locationBundle==='function'&&typeof window.TGGWorldSync?.missionStoryBundle==='function');test('world property vehicle bridge',typeof window.TGGWorldSync?.propertyMarket==='function'&&typeof window.TGGWorldSync?.propertyUpgrades==='function'&&typeof window.TGGWorldSync?.vehicleProgression==='function'&&typeof window.TGGWorldSync?.vehicleBundle==='function'&&typeof window.TGGWorldSync?.worldAssetsBundle==='function');
    test('business api',!!window.TGGBusiness&&typeof window.TGGBusiness.open==='function'&&typeof window.TGGBusiness.select==='function'&&typeof window.TGGBusiness.sync==='function');test('business catalog',Array.isArray(window.TGGBusiness?.catalog)&&window.TGGBusiness.catalog.length>=4);test('business persistence',Array.isArray(window.TGGBusiness?.state?.discovered)&&typeof window.TGGBusiness?.save==='function'&&typeof window.TGGBusiness?.load==='function');test('business screen',!!document.getElementById('businessBoard')&&!!document.getElementById('businessBtn'));test('business assets loader',typeof window.TGGBusiness?.loadAssets==='function');test('business assets state',!!window.TGGBusiness?.state?.assets&&typeof window.TGGBusiness.state.assets==='object');test('live city activity snapshot',typeof window.TGGBusiness?.activitySnapshot==='function'&&window.TGGBusiness.activitySnapshot()?.readOnly===true);test('property readonly inspect',typeof window.TGGBusiness?.inspectProperty==='function');test('vehicle readonly inspect',typeof window.TGGBusiness?.inspectVehicle==='function');test('city assets hotspot',!!document.getElementById('cityAssetsBtn'));
    const p=window.TGGGame?.getState?.();test('player state',!!p&&typeof p.level==='number'&&typeof p.cash==='number'&&typeof p.xp==='number');
    const c=window.TGGCareer?.career;test('career state',!!c&&typeof c.studioLevel==='number'&&typeof c.reputation==='number');
    const content=window.TGGContent?.content;test('content missions',Array.isArray(content?.missions)&&content.missions.length>=3);test('content progression',typeof window.TGGContent?.advance==='function'&&typeof window.TGGContent?.start==='function');
    test('expansion activities',Array.isArray(window.TGGExpansion?.activities)&&window.TGGExpansion.activities.length>=3);
    test('progression catalog',Array.isArray(window.TGGProgression?.achievements)&&window.TGGProgression.achievements.length>=7);test('progression state',Array.isArray(window.TGGProgression?.state?.unlocked));test('progression sync',typeof window.TGGProgression?.sync==='function');
    test('chain catalog',Array.isArray(window.TGGChains?.chains)&&window.TGGChains.chains.length>=2);test('chain ui',typeof window.TGGChainUI?.start==='function');
    test('district catalog',Array.isArray(window.TGGDistricts?.districts)&&window.TGGDistricts.districts.length>=3);test('district access',typeof window.TGGDistricts?.canEnter==='function');
    test('save validator',typeof window.TGGSave?.report==='function'&&typeof window.TGGSave?.repair==='function');
    test('inventory catalog',Array.isArray(window.TGGInventory?.catalog)&&window.TGGInventory.catalog.length>=4);test('inventory persistence',typeof window.TGGInventory?.save==='function'&&typeof window.TGGInventory?.load==='function');
    test('crew catalog',Array.isArray(window.TGGCrew?.catalog)&&window.TGGCrew.catalog.length>=3);test('crew persistence',typeof window.TGGCrew?.save==='function'&&typeof window.TGGCrew?.load==='function');test('crew bonus',typeof window.TGGCrew?.bonus==='function');
    test('events catalog',Array.isArray(window.TGGEvents?.events)&&window.TGGEvents.events.length>=3);test('events persistence',typeof window.TGGEvents?.save==='function'&&typeof window.TGGEvents?.load==='function');test('events run',typeof window.TGGEvents?.run==='function');
    test('city mastery api',typeof window.TGGEvents?.totalRuns==='function'&&typeof window.TGGEvents?.mastery==='function'&&typeof window.TGGEvents?.cityProfile==='function');
    const cityProfile=window.TGGEvents?.cityProfile?.()||{};test('city mastery state',typeof cityProfile.totalRuns==='number'&&typeof cityProfile.streak==='number'&&typeof cityProfile.bestStreak==='number');
    test('city mastery achievements',['city-regular','city-known','city-headliner'].every(id=>window.TGGProgression?.achievements?.some(a=>a.id===id)));
    test('circuits api',!!window.TGGCircuits&&typeof window.TGGCircuits.start==='function'&&typeof window.TGGCircuits.onEventComplete==='function'&&typeof window.TGGCircuits.status==='function'&&typeof window.TGGCircuits.variant==='function');
    test('circuits persistence',window.TGGSave?.keys?.circuits==='tgg-circuits-v1'&&Array.isArray(window.TGGCircuits?.state?.completed));
    const cypherVariant=window.TGGCircuits?.variant?.('street-cypher')||{};test('event variant cosmetic',cypherVariant.cosmeticOnly===true&&cypherVariant.rewardMultiplier===1);
    test('circuit achievements',['first-circuit','city-circuit'].every(id=>window.TGGProgression?.achievements?.some(a=>a.id===id)));
    test('district story api',!!window.TGGDistrictStory&&typeof window.TGGDistrictStory.start==='function'&&typeof window.TGGDistrictStory.currentBeat==='function'&&typeof window.TGGDistrictStory.refreshRemoteStory==='function');
    test('district story persistence',window.TGGSave?.keys?.districtStory==='tgg-district-story-v1'&&Array.isArray(window.TGGDistrictStory?.state?.completed));
    test('district story route',Array.isArray(window.TGGDistrictStory?.routes)&&window.TGGDistrictStory.routes.some(r=>r.id==='city-story-lap'&&r.circuit==='city-run'));
    test('district story achievement',window.TGGProgression?.achievements?.some(a=>a.id==='district-story'));
    test('route memory api',!!window.TGGRouteMemory&&typeof window.TGGRouteMemory.recordBeat==='function'&&typeof window.TGGRouteMemory.encounterCurrent==='function'&&typeof window.TGGRouteMemory.refreshRemoteMemory==='function');
    test('route memory persistence',window.TGGSave?.keys?.routeMemory==='tgg-route-memory-v1'&&Array.isArray(window.TGGRouteMemory?.state?.encounters));
    test('route memory npcs',['m','producer','dj'].every(id=>!!window.TGGRouteMemory?.npcs?.[id]));
    test('route memory achievement',window.TGGProgression?.achievements?.some(a=>a.id==='know-the-city'));
    test('relationship api',typeof window.TGGRouteMemory?.relationship==='function'&&typeof window.TGGRouteMemory?.dialogue==='function'&&typeof window.TGGRouteMemory?.syncRelationships==='function');
    test('relationship state',!!window.TGGRouteMemory?.state?.relationships&&typeof window.TGGRouteMemory.state.relationships==='object');
    test('trusted contact achievement',window.TGGProgression?.achievements?.some(a=>a.id==='trusted-contact'));
    test('contact ops api',!!window.TGGContactOps&&typeof window.TGGContactOps.available==='function'&&typeof window.TGGContactOps.start==='function'&&typeof window.TGGContactOps.onEventComplete==='function');
    test('contact ops single store',!!window.TGGRouteMemory?.state?.opportunities&&typeof window.TGGRouteMemory.state.opportunities==='object');
    test('contact ops catalog',Array.isArray(window.TGGContactOps?.opportunities)&&window.TGGContactOps.opportunities.length>=3);
    test('first opportunity achievement',window.TGGProgression?.achievements?.some(a=>a.id==='first-opportunity'));
    const economy=window.TGGEconomy?.reward?.({cash:100,xp:25,rep:5});test('economy normalization',!!economy&&economy.cash>=100&&economy.xp>=25&&economy.rep>=5&&economy.crew&&economy.crew.cash>=0,'shared reward normalization available');
    const integrity=window.TGGV12IntegrityResult||window.TGGV12Integrity?.run?.();test('v12 integrity',!!integrity?.passed);
    test('bridge snapshot',typeof window.TGGBridge?.snapshot==='function');
    const passed=checks.every(x=>x.pass);window.TGGReleaseQA={checks,passed,run};return window.TGGReleaseQA;
  }
  window.TGGReleaseQA={checks,passed:false,run};
})();
