(() => {
  const checks=[]; const test=(name,pass,detail='')=>checks.push({name,pass:!!pass,detail});
  function run(){
    checks.length=0;
    test('game api',!!window.TGGGame);
    test('v2 walking api',typeof window.TGGGame?.getWalkingState==='function'&&typeof window.TGGGame?.setWalkKey==='function');
    const walkTune=window.TGGGame?.getWalkTuning?.()||{};test('v2 walking tune',Number(walkTune.walkSpeed)>0&&Number(walkTune.sprintSpeed)>Number(walkTune.walkSpeed));
    test('v2 player dynamics',typeof window.TGG3D?.setPlayerDynamics==='function'&&typeof window.TGG3D?.getPlayerDynamics==='function');
    const carSpawn=window.TGG3D?.getCarPercent?.();
    test('v204 car position api',Number.isFinite(carSpawn?.x)&&Number.isFinite(carSpawn?.y));
    test('v204 starter car safe spawn',!!carSpawn&&window.TGG3D?.canMovePercent?.(carSpawn.x,carSpawn.y,true)===true);
    test('v204 drive input api',typeof window.TGGGame?.driveVehicle==='function'&&typeof window.TGGGame?.setDriveKey==='function');
    test('v205 car recovery api',typeof window.TGGGame?.recoverVehicle==='function');
    test('v205 reset car control',!!document.getElementById('recoverCarBtn'));
    const driveState=window.TGGGame?.getDrivingState?.()||{};
    test('v206 boost runtime',typeof driveState.boostEnergy==='number'&&driveState.boostEnergy>=0&&driveState.boostEnergy<=100);
    test('v206 boost hud',!!document.getElementById('boostValue')&&!!document.getElementById('boostFill'));
    test('v206 unified job nav',typeof window.TGGStreetContacts?.closest==='function'&&typeof window.TGGStreetContacts?.focusNearest==='function'&&typeof window.TGGStreetContacts?.getNavTarget==='function');
    test('v207 boost flames',Array.isArray(window.TGG3D?.car?.userData?.boostFlames)&&window.TGG3D.car.userData.boostFlames.length===2);
    test('v207 sport car visuals',!!window.TGG3D?.car?.userData?.spoiler&&!!window.TGG3D?.car?.userData?.underGlow&&!!window.TGG3D?.car?.userData?.boostGlow);
    test('v208 street life api',!!window.TGGStreetLife&&typeof window.TGGStreetLife.status==='function'&&typeof window.TGGStreetLife.relationshipLine==='function');
    test('v208 pedestrian horn reaction',typeof window.TGG3D?.reactToHorn==='function');
    test('v208 contact object bridge',typeof window.TGGStreetContacts?.getObject==='function');
    test('v208 mission depth',window.TGGContent?.content?.missions?.every(m=>Number(m.goal)>=2)===true);
    test('v208 street life css',!!document.querySelector('link[href*="v208-street-life.css"]'));
    test('v209 city action api',!!window.TGGCityAction&&typeof window.TGGCityAction.handleImpact==='function'&&typeof window.TGGCityAction.showScene==='function');
    test('v209 traffic bridge',typeof window.TGG3D?.nearestTraffic==='function'&&typeof window.TGGGame?.vehicleImpact==='function');
    test('v209 mission handoff',typeof window.TGGStreetContacts?.focusMission==='function'&&typeof window.TGGStreetContacts?.contactForMission==='function');
    test('v209 city action css',!!document.querySelector('link[href*="v209-city-action.css"]'));
    const cityDepth=window.TGGCityDepth?.status?.()||{};
    test('v210 city depth api',!!window.TGGCityDepth&&typeof window.TGGCityDepth.boot==='function');
    test('v210 traffic lights',Number(cityDepth.trafficLights)>=8);
    test('v210 billboards',Number(cityDepth.billboards)>=3);
    const living=window.TGGLivingTraffic?.status?.()||{};
    test('v211 living traffic api',!!window.TGGLivingTraffic&&typeof window.TGGLivingTraffic.updateTraffic==='function'&&typeof window.TGGLivingTraffic.signal==='function');
    test('v211 traffic control bridge',typeof window.TGG3D?.setTrafficSpeed==='function'&&Array.isArray(window.TGG3D?.traffic));
    test('v211 signal bridge',typeof window.TGGCityDepth?.signalForAxis==='function');
    test('v211 traffic hud',!!document.getElementById('livingTrafficHud'));
    test('v211 traffic state',Number(living?.traffic?.count)>=4);
    const mega=window.TGGV212?.status?.()||{};
    test('v212 mega api',!!window.TGGV212&&typeof window.TGGV212.repairCar==='function'&&typeof window.TGGV212.damage==='function');
    test('v212 100 layers',Array.isArray(window.TGGV212?.layers)&&window.TGGV212.layers.length===100);
    test('v212 condition state',Number(mega.condition)>=0&&Number(mega.condition)<=100);
    test('v212 repair control',!!document.getElementById('repairCarBtn'));
    test('v212 drive hud',!!document.getElementById('megaDriveHud'));
    test('v212 help overlay',!!document.getElementById('megaHelpBtn')&&!!document.getElementById('megaHelpPanel'));
    test('v212 mega css',!!document.querySelector('link[href*="v212-mega-100.css"]'));
    const polish=window.TGGV213?.status?.()||{};
    test('v213 world polish api',!!window.TGGV213&&typeof window.TGGV213.boot==='function'&&typeof window.TGGV213.impactSparks==='function');
    test('v213 100 layers',Array.isArray(window.TGGV213?.layers)&&window.TGGV213.layers.length===100);
    test('v213 world props',Number(polish.props)>=20);
    test('v213 traffic population',Number(polish.extraTraffic)>=4&&Number(polish.trafficTotal)>=10);
    test('v213 pedestrian population',Number(polish.extraPedestrians)>=4&&Number(polish.pedestrianTotal)>=10);
    test('v213 world polish css',!!document.querySelector('link[href*="v213-world-polish.css"]'));
    const harden=window.TGGV214?.status?.()||{};
    test('v214 hardening api',!!window.TGGV214&&typeof window.TGGV214.snapshot==='function'&&typeof window.TGGV214.guardPlayerState==='function');
    test('v214 100 layers',Array.isArray(window.TGGV214?.layers)&&window.TGGV214.layers.length===100);
    test('v214 diagnostics control',!!document.getElementById('v214DiagBtn')&&!!document.getElementById('v214DiagPanel'));
    test('v214 fullscreen control',!!document.getElementById('v214FullBtn'));
    test('v214 storage health',harden.storageHealthy!==false);
    test('v214 hardening css',!!document.querySelector('link[href*="v214-playtest-hardening.css"]'));
    const depth=window.TGGV215?.status?.()||{};
    test('v215 character mission api',!!window.TGGV215&&typeof window.TGGV215.setEmote==='function'&&typeof window.TGGV215.scoreMission==='function');
    test('v215 100 layers',Array.isArray(window.TGGV215?.layers)&&window.TGGV215.layers.length===100);
    test('v215 emote control',!!document.getElementById('v215EmoteBtn'));
    test('v215 mission hud',!!document.getElementById('v215MissionHud'));
    test('v215 mission score card',!!document.getElementById('v215MissionCard'));
    test('v215 character mission css',!!document.querySelector('link[href*="v215-character-mission.css"]'));
    const models=window.TGGV216?.status?.()||{};
    test('v216 model polish api',!!window.TGGV216&&typeof window.TGGV216.decorateHuman==='function'&&typeof window.TGGV216.addCarDetail==='function');
    test('v216 100 layers',Array.isArray(window.TGGV216?.layers)&&window.TGGV216.layers.length===100);
    test('v216 model polish css',!!document.querySelector('link[href*="v216-model-polish.css"]'));
    test('v216 model population api',typeof window.TGGV216?.decoratePopulation==='function');
    const interiors=window.TGGV217?.status?.()||{};
    test('v217 interior depth api',!!window.TGGV217&&typeof window.TGGV217.startActivity==='function'&&typeof window.TGGV217.decorateActive==='function');
    test('v217 100 layers',Array.isArray(window.TGGV217?.layers)&&window.TGGV217.layers.length===100);
    test('v217 interior overlay',!!document.getElementById('v217InteriorOverlay'));
    test('v217 interior depth css',!!document.querySelector('link[href*="v217-interior-depth.css"]'));
    test('v2 final runtime',window.TGGFinalBuild?.version==='V2.17 CITY + INTERIOR DEPTH 100');
    test('v2 movement hud',!!document.getElementById('playerMoveHud')&&!!document.getElementById('walkModeValue')&&!!document.getElementById('walkSpeedValue'));
    test('v2 sprint control',!!document.getElementById('sprintBtn'));test('v202 world gameplay',!!window.TGGWorldGameplay&&typeof window.TGGWorldGameplay.getNavTarget==='function'&&typeof window.TGGWorldGameplay.performObjective==='function');test('v202 world objective hud',!!document.getElementById('worldObjective'));test('v203 street contacts',!!window.TGGStreetContacts&&Array.isArray(window.TGGStreetContacts.contacts)&&window.TGGStreetContacts.contacts.length>=3&&typeof window.TGGStreetContacts.startContact==='function');test('v203 contact hud',!!document.getElementById('streetContactCard'));test('career api',!!window.TGGCareer);test('content api',!!window.TGGContent);test('expansion api',!!window.TGGExpansion);test('progression api',!!window.TGGProgression);test('bridge api',!!window.TGGBridge);test('chain api',!!window.TGGChains);test('district api',!!window.TGGDistricts);test('save api',!!window.TGGSave);test('inventory api',!!window.TGGInventory);test('crew api',!!window.TGGCrew);test('events api',!!window.TGGEvents);test('economy api',!!window.TGGEconomy&&typeof window.TGGEconomy.apply==='function');test('avatar api',!!window.TGGAvatar&&typeof window.TGGAvatar.get==='function'&&typeof window.TGGAvatar.save==='function');test('world sync api',!!window.TGGWorldSync&&typeof window.TGGWorldSync.snapshot==='function'&&typeof window.TGGWorldSync.setTransport==='function'&&typeof window.TGGWorldSync.sync==='function');
    ['menu','creator','avatar','game','career','contentBoard','expansionBoard','progressionBoard','inventoryBoard','crewBoard','eventsBoard','bridge','pause','hud'].forEach(id=>test('dom:'+id,!!document.getElementById(id)));
    ['newGame','continueGame','startGame','avatarStart','characterBtn','avatarDone','avatarBack','rotateLeft','rotateRight','missionBtn','careerBtn','contentBtn','advanceContentBtn','expansionBtn','progressionBtn','inventoryBtn','crewBtn','eventsBtn','bridgeBtn','worldSyncBtn','chainBtn','saveBtn','pauseBtn','resumeBtn','menuBtn','recordBtn','mixtapeBtn','upgradeBtn'].forEach(id=>test('control:'+id,!!document.getElementById(id)));
    test('local storage',typeof localStorage!=='undefined');const av=window.TGGAvatar?.get?.()||{};test('avatar state',typeof av.skin==='string'&&typeof av.hair==='string'&&typeof av.top==='string'&&typeof av.accent==='string');test('avatar save integration',window.TGGSave?.keys?.avatar==='tgg-avatar-v1');const ws=window.TGGWorldSync?.snapshot?.()||{};test('world sync packet',ws.schema==='tgg-world-sync-v1'&&ws.version==='1.12.0'&&!!ws.player&&!!ws.avatar&&!!ws.career);test('world sync offline default',window.TGGWorldSync?.status?.().status==='offline_ready');const wp=window.TGGWorldSync?.positionPayload?.()||{};test('world presence packet',!!wp.position&&!!wp.rotation&&!!wp.activity&&wp.position.space==='city_percent');test('world presence bridge',typeof window.TGGWorldSync?.heartbeat==='function'&&typeof window.TGGWorldSync?.presenceBundle==='function'&&typeof window.TGGWorldSync?.nextMoves==='function');test('world career economy bridge',typeof window.TGGWorldSync?.careerBundle==='function'&&typeof window.TGGWorldSync?.economyBundle==='function'&&typeof window.TGGWorldSync?.walletReconcile==='function'&&typeof window.TGGWorldSync?.readRemoteState==='function');test('world inventory equipment bridge',typeof window.TGGWorldSync?.remoteInventory==='function'&&typeof window.TGGWorldSync?.equipRemoteItem==='function');test('world social crew bridge',typeof window.TGGWorldSync?.socialBundle==='function'&&typeof window.TGGWorldSync?.crewActivity==='function'&&typeof window.TGGWorldSync?.crewRides==='function'&&typeof window.TGGWorldSync?.crewBundle==='function'&&typeof window.TGGWorldSync?.contactOffers==='function');test('world mission story bridge',typeof window.TGGWorldSync?.creativeMissions==='function'&&typeof window.TGGWorldSync?.npcEncounters==='function'&&typeof window.TGGWorldSync?.storyControl==='function'&&typeof window.TGGWorldSync?.memoryHistory==='function'&&typeof window.TGGWorldSync?.locationBundle==='function'&&typeof window.TGGWorldSync?.missionStoryBundle==='function');test('world property vehicle bridge',typeof window.TGGWorldSync?.propertyMarket==='function'&&typeof window.TGGWorldSync?.propertyUpgrades==='function'&&typeof window.TGGWorldSync?.vehicleProgression==='function'&&typeof window.TGGWorldSync?.vehicleBundle==='function'&&typeof window.TGGWorldSync?.worldAssetsBundle==='function');
    test('business api',!!window.TGGBusiness&&typeof window.TGGBusiness.open==='function'&&typeof window.TGGBusiness.select==='function'&&typeof window.TGGBusiness.sync==='function');test('business catalog',Array.isArray(window.TGGBusiness?.catalog)&&window.TGGBusiness.catalog.length>=4);test('business persistence',Array.isArray(window.TGGBusiness?.state?.discovered)&&typeof window.TGGBusiness?.save==='function'&&typeof window.TGGBusiness?.load==='function');test('business screen',!!document.getElementById('businessBoard')&&!!document.getElementById('businessBtn'));test('business assets loader',typeof window.TGGBusiness?.loadAssets==='function');test('business assets state',!!window.TGGBusiness?.state?.assets&&typeof window.TGGBusiness.state.assets==='object');test('live city activity snapshot',typeof window.TGGBusiness?.activitySnapshot==='function'&&window.TGGBusiness.activitySnapshot()?.readOnly===true);test('property readonly inspect',typeof window.TGGBusiness?.inspectProperty==='function');test('vehicle readonly inspect',typeof window.TGGBusiness?.inspectVehicle==='function');test('city assets hotspot',!!document.getElementById('cityAssetsBtn'));
    const p=window.TGGGame?.getState?.();test('player state',!!p&&typeof p.level==='number'&&typeof p.cash==='number'&&typeof p.xp==='number');
    const c=window.TGGCareer?.career;test('career state',!!c&&typeof c.studioLevel==='number'&&typeof c.reputation==='number');
    const content=window.TGGContent?.content;test('content missions',Array.isArray(content?.missions)&&content.missions.length>=3);test('content progression',typeof window.TGGContent?.advance==='function'&&typeof window.TGGContent?.start==='function');
    test('expansion activities',Array.isArray(window.TGGExpansion?.activities)&&window.TGGExpansion.activities.length>=3);
    test('progression catalog',Array.isArray(window.TGGProgression?.achievements)&&window.TGGProgression.achievements.length>=7);test('progression state',Array.isArray(window.TGGProgression?.state?.unlocked));test('progression sync',typeof window.TGGProgression?.sync==='function');
    test('chain catalog',Array.isArray(window.TGGChains?.chains)&&window.TGGChains.chains.length>=2);test('chain ui',typeof window.TGGChainUI?.start==='function');
    test('district catalog',Array.isArray(window.TGGDistricts?.districts)&&window.TGGDistricts.districts.length>=3);test('district access',typeof window.TGGDistricts?.canEnter==='function');
    test('save validator',typeof window.TGGSave?.report==='function'&&typeof window.TGGSave?.repair==='function');
    test('inventory catalog',Array.isArray(window.TGGInventory?.catalog)&&window.TGGInventory.catalog.length>=4);test('inventory persistence',typeof window.TGGInventory?.save==='function'&&typeof window.TGGInventory?.load==='function');
    test('crew catalog',Array.isArray(window.TGGCrew?.catalog)&&window.TGGCrew.catalog.length>=3);test('crew persistence',typeof window.TGGCrew?.save==='function'&&typeof window.TGGCrew?.load==='function');test('crew bonus',typeof window.TGGCrew?.bonus==='function');
    test('events catalog',Array.isArray(window.TGGEvents?.events)&&window.TGGEvents.events.length>=3);test('events persistence',typeof window.TGGEvents?.save==='function'&&typeof window.TGGEvents?.load==='function');test('events run',typeof window.TGGEvents?.run==='function');
    test('city mastery api',typeof window.TGGEvents?.totalRuns==='function'&&typeof window.TGGEvents?.mastery==='function'&&typeof window.TGGEvents?.cityProfile==='function');
    const cityProfile=window.TGGEvents?.cityProfile?.()||{};test('city mastery state',typeof cityProfile.totalRuns==='number'&&typeof cityProfile.streak==='number'&&typeof cityProfile.bestStreak==='number');
    test('city mastery achievements',['city-regular','city-known','city-headliner'].every(id=>window.TGGProgression?.achievements?.some(a=>a.id===id)));
    test('circuits api',!!window.TGGCircuits&&typeof window.TGGCircuits.start==='function'&&typeof window.TGGCircuits.onEventComplete==='function'&&typeof window.TGGCircuits.status==='function'&&typeof window.TGGCircuits.variant==='function');
    test('circuits persistence',window.TGGSave?.keys?.circuits==='tgg-circuits-v1'&&Array.isArray(window.TGGCircuits?.state?.completed));
    const cypherVariant=window.TGGCircuits?.variant?.('street-cypher')||{};test('event variant cosmetic',cypherVariant.cosmeticOnly===true&&cypherVariant.rewardMultiplier===1);
    test('circuit achievements',['first-circuit','city-circuit'].every(id=>window.TGGProgression?.achievements?.some(a=>a.id===id)));
    test('district story api',!!window.TGGDistrictStory&&typeof window.TGGDistrictStory.start==='function'&&typeof window.TGGDistrictStory.currentBeat==='function'&&typeof window.TGGDistrictStory.refreshRemoteStory==='function');
    test('district story persistence',window.TGGSave?.keys?.districtStory==='tgg-district-story-v1'&&Array.isArray(window.TGGDistrictStory?.state?.completed));
    test('district story route',Array.isArray(window.TGGDistrictStory?.routes)&&window.TGGDistrictStory.routes.some(r=>r.id==='city-story-lap'&&r.circuit==='city-run'));
    test('district story achievement',window.TGGProgression?.achievements?.some(a=>a.id==='district-story'));
    test('route memory api',!!window.TGGRouteMemory&&typeof window.TGGRouteMemory.recordBeat==='function'&&typeof window.TGGRouteMemory.encounterCurrent==='function'&&typeof window.TGGRouteMemory.refreshRemoteMemory==='function');
    test('route memory persistence',window.TGGSave?.keys?.routeMemory==='tgg-route-memory-v1'&&Array.isArray(window.TGGRouteMemory?.state?.encounters));
    test('route memory npcs',['m','producer','dj'].every(id=>!!window.TGGRouteMemory?.npcs?.[id]));
    test('route memory achievement',window.TGGProgression?.achievements?.some(a=>a.id==='know-the-city'));
    test('relationship api',typeof window.TGGRouteMemory?.relationship==='function'&&typeof window.TGGRouteMemory?.dialogue==='function'&&typeof window.TGGRouteMemory?.syncRelationships==='function');
    test('relationship state',!!window.TGGRouteMemory?.state?.relationships&&typeof window.TGGRouteMemory.state.relationships==='object');
    test('trusted contact achievement',window.TGGProgression?.achievements?.some(a=>a.id==='trusted-contact'));
    test('contact ops api',!!window.TGGContactOps&&typeof window.TGGContactOps.available==='function'&&typeof window.TGGContactOps.start==='function'&&typeof window.TGGContactOps.onEventComplete==='function');
    test('contact ops single store',!!window.TGGRouteMemory?.state?.opportunities&&typeof window.TGGRouteMemory.state.opportunities==='object');
    test('contact ops catalog',Array.isArray(window.TGGContactOps?.opportunities)&&window.TGGContactOps.opportunities.length>=3);
    test('first opportunity achievement',window.TGGProgression?.achievements?.some(a=>a.id==='first-opportunity'));
    const economy=window.TGGEconomy?.reward?.({cash:100,xp:25,rep:5});test('economy normalization',!!economy&&economy.cash>=100&&economy.xp>=25&&economy.rep>=5&&economy.crew&&economy.crew.cash>=0,'shared reward normalization available');
    const integrity=window.TGGV12IntegrityResult||window.TGGV12Integrity?.run?.();test('v12 integrity',!!integrity?.passed);
    test('bridge snapshot',typeof window.TGGBridge?.snapshot==='function');
    const passed=checks.every(x=>x.pass);window.TGGReleaseQA={checks,passed,run};return window.TGGReleaseQA;
  }
  window.TGGReleaseQA={checks,passed:false,run};
})();
