(() => {
  const forge=globalThis.__V235ForgeUnderTest;
  const assert=(ok,msg)=>{if(!ok)throw new Error(msg)};
  assert(forge,'V2.35 NPC Crowd Forge adapter API must exist');
  assert(Array.isArray(forge.layers)&&forge.layers.length===100,'exact 100 NPC layers');
  assert(typeof forge.status==='function','status API');
  assert(typeof forge.rebuild==='function','rebuild API');
  assert(typeof forge.setDistrict==='function','district API');
  assert(typeof forge.setEnabled==='function','enabled API');
  assert(typeof forge.clear==='function','clear API');
  assert(typeof forge.spawnAudience==='function','audience API');
  assert(Array.isArray(forge.districts)&&forge.districts.includes('downtown')&&forge.districts.includes('studio-row')&&forge.districts.includes('media'),'districts');
  const s=forge.status();
  assert(s.version==='V2.35 TGG NPC + CROWD FORGE 100','version');
  assert(s.mode==='native-npc-crowd-forge','mode');
  assert(s.enabled===true,'enabled default');
  assert(s.district==='downtown','downtown default');
  assert(s.layerCount===100,'layer count');
  return true;
})();