import fs from 'node:fs';
import assert from 'node:assert/strict';
const root=new URL('.',import.meta.url);
const read=(name)=>fs.readFileSync(new URL(name,root),'utf8');
const index=read('index.html');
const js=read('photoreal-core.js');
const css=read('photoreal-core.css');
const runtime=JSON.parse(read('runtime-version.json'));
assert.match(index,/photoreal-core\.css/);
assert.match(index,/photoreal-core\.js/);
assert.match(index,/V2\.45 PHOTOREAL CORE/);
assert.match(js,/ACESFilmicToneMapping/);
assert.match(js,/MeshPhysicalMaterial/);
assert.match(js,/adaptive-pixel-ratio/);
assert.match(js,/v245-realism-sky/);
assert.match(css,/v245CinematicOverlay/);
assert.equal(runtime.canonical_runtime,'V2.45 PHOTOREAL CORE BULK');
for(const feature of ['photoreal_core','aces_filmic','adaptive_graphics_quality'])assert.ok(runtime.features.includes(feature),feature);
console.log(JSON.stringify({ok:true,version:runtime.canonical_runtime,checks:12}));
